### ISSUE TITLE
Twitch Bit Reward emotes cause disconnect

### ISSUE THREAD

**Issue by ZeekDaGeek** [blay09/TwitchIntegration#27]
Twitch added a feature to make it so you can unlock emotes through bits. Any time any of these new emotes are used they cause Twitch Integration to disconnect.

The emote ID is a massive chunk of garbage instead of a standard numerical ID and has no emote set:
![dUX1Y](https://user-images.githubusercontent.com/1709288/83331455-c2a80d00-a253-11ea-8913-1d344c5600b7.png)

Here's a sample ofthe errors in console when the emotes are used.

```
[08:43:32] [IRCConnection (irc.chat.twitch.tv)/ERROR]: Unhandled exception: 
java.lang.NumberFormatException: For input string: "emotesv2_0588a3ae76d94e008e94824806cbf241"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_51]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_51]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_51]
	at net.blay09.mods.twitchintegration.tmi.TwitchUser.parseMessageTags(TwitchUser.java:82) ~[TwitchUser.class:?]
	at net.blay09.mods.twitchintegration.tmi.TwitchUser.fromMessage(TwitchUser.java:54) ~[TwitchUser.class:?]
	at net.blay09.mods.twitchintegration.tmi.TMIClient$1.onChannelChat(TMIClient.java:142) [TMIClient$1.class:?]
	at net.blay09.mods.twitchintegration.irc.IRCConnection.handleMessage(IRCConnection.java:192) [IRCConnection.class:?]
	at net.blay09.mods.twitchintegration.irc.IRCConnection.run(IRCConnection.java:157) [IRCConnection.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[08:46:36] [IRCConnection (irc.chat.twitch.tv)/ERROR]: Unhandled exception: 
java.lang.NumberFormatException: For input string: "emotesv2_0588a3ae76d94e008e94824806cbf241"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_51]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_51]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_51]
	at net.blay09.mods.twitchintegration.tmi.TwitchUser.parseMessageTags(TwitchUser.java:82) ~[TwitchUser.class:?]
	at net.blay09.mods.twitchintegration.tmi.TwitchUser.fromMessage(TwitchUser.java:54) ~[TwitchUser.class:?]
	at net.blay09.mods.twitchintegration.tmi.TMIClient$1.onChannelChat(TMIClient.java:142) [TMIClient$1.class:?]
	at net.blay09.mods.twitchintegration.irc.IRCConnection.handleMessage(IRCConnection.java:192) [IRCConnection.class:?]
	at net.blay09.mods.twitchintegration.irc.IRCConnection.run(IRCConnection.java:157) [IRCConnection.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[08:49:01] [IRCConnection (irc.chat.twitch.tv)/ERROR]: Unhandled exception: 
java.lang.NumberFormatException: For input string: "emotesv2_85fb8aa3e223487c9d9ba16c2a814e01"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_51]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_51]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_51]
	at net.blay09.mods.twitchintegration.tmi.TwitchUser.parseMessageTags(TwitchUser.java:82) ~[TwitchUser.class:?]
	at net.blay09.mods.twitchintegration.tmi.TwitchUser.fromMessage(TwitchUser.java:54) ~[TwitchUser.class:?]
	at net.blay09.mods.twitchintegration.tmi.TMIClient$1.onChannelChat(TMIClient.java:142) [TMIClient$1.class:?]
	at net.blay09.mods.twitchintegration.irc.IRCConnection.handleMessage(IRCConnection.java:192) [IRCConnection.class:?]
	at net.blay09.mods.twitchintegration.irc.IRCConnection.run(IRCConnection.java:157) [IRCConnection.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[08:49:58] [IRCConnection (irc.chat.twitch.tv)/ERROR]: Unhandled exception: 
java.lang.NumberFormatException: For input string: "emotesv2_0592a4110eaf4a80b231e147fa60e380"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_51]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_51]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_51]
	at net.blay09.mods.twitchintegration.tmi.TwitchUser.parseMessageTags(TwitchUser.java:82) ~[TwitchUser.class:?]
	at net.blay09.mods.twitchintegration.tmi.TwitchUser.fromMessage(TwitchUser.java:54) ~[TwitchUser.class:?]
	at net.blay09.mods.twitchintegration.tmi.TMIClient$1.onChannelChat(TMIClient.java:142) [TMIClient$1.class:?]
	at net.blay09.mods.twitchintegration.irc.IRCConnection.handleMessage(IRCConnection.java:192) [IRCConnection.class:?]
	at net.blay09.mods.twitchintegration.irc.IRCConnection.run(IRCConnection.java:157) [IRCConnection.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[08:52:47] [IRCConnection (irc.chat.twitch.tv)/ERROR]: Unhandled exception: 
java.lang.NumberFormatException: For input string: "emotesv2_34804006d2404fd188751e6445bb2a76"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_51]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_51]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_51]
	at net.blay09.mods.twitchintegration.tmi.TwitchUser.parseMessageTags(TwitchUser.java:82) ~[TwitchUser.class:?]
	at net.blay09.mods.twitchintegration.tmi.TwitchUser.fromMessage(TwitchUser.java:54) ~[TwitchUser.class:?]
	at net.blay09.mods.twitchintegration.tmi.TMIClient$1.onChannelChat(TMIClient.java:142) [TMIClient$1.class:?]
	at net.blay09.mods.twitchintegration.irc.IRCConnection.handleMessage(IRCConnection.java:192) [IRCConnection.class:?]
	at net.blay09.mods.twitchintegration.irc.IRCConnection.run(IRCConnection.java:157) [IRCConnection.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by BlayTheNinth** [comment]
Should be fixed, needs both Chat Tweaks and Twitch Chat Integration to be updated
